### ISSUE TITLE
Request for a working usage example

### ISSUE THREAD

**Issue by cyclaero** [m-lima/cracker#4]
Please may I ask for a working usage example? A simple test using the md5 hash of my first name "rolf" did not work out. I am also in doubt abut the length parameter. On a Mac Mini (late 2014), I did:

`./cracker -e "rolf"`

    6c36a051b929758aec2d67fd9ee09f4e

`./cracker -t "6c36a051b929758aec2d67fd9ee09f4e"`

    Initializing cracker on GPU
      Prefix:           
      Length:           12
      Target count:     1
      Parallel kernels: 10000000
      Iterations:       100000
      Build defines:    -D CONST_BEGIN=0 -D CONST_END=12 -D CONST_SUFFIX=96ul -D CONST_PREFIX_DECIMAL_PLACES=5 -D CONST_TARGET_COUNT=1
    
    Preparing
    Done preparing
    Executing
    Processed  100%
    Done
    
    Running stats:
      Time elapsed cracking hashes:   1h 3m 44.999s
      Average hashes per millisecond: 261.44 thousand
    
    Results:
    6c36a051b929758aec2d67fd9ee09f4e :: NOT FOUND
    Rainbow table hits: 0 (0%)
    Cracker hits: 0 (0%)
    Values found: 0/1 (0%)
    
    Not saving entries to the rainbow table

**Comment by mlimat** [comment]
Hi @cyclaero,
This software works with numeric values only. And because of that, I have highly optimized it for this data space.
This is what the length is for. That is, how many digits the target is supposed to have.

So, as requested, this is a working example:
```
$ cracker -e 1234567890
e807f1fcf82d132f9bb018ca6738a19f
$ cracker -t e807f1fcf82d132f9bb018ca6738a19f -l 10
...
Results:
e807f1fcf82d132f9bb018ca6738a19f :: 1234567890 [cracked]
Rainbow table hits: 0 (0%)
Cracker hits: 1 (100%)
Values found: 1/1 (100%)
```

Also, if you know the first digits, you can specify that as well
```
$ cracker -e 1234567890 | ./cracker -l 10 -p 123
```

**Comment by cyclaero** [comment]
Thank you very much for your quick response. This explains everything.
